language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk11

script:
  - ./gradlew clean
  - ./gradlew build -x test
  - ./gradlew test

after_success:
  - bash <(curl -s https://codecov.io/bash)
